### ISSUE TITLE
Crash from Incendiary Lance ver 1.19.2-1.4.0

### ISSUE THREAD

**Issue by afloofflam** [JmKopecky/ProgressableAttributesAndAbilities#1]
Hello!

Really loving the mod. However I received the error in italics below when loading an existing world once I updated to version 1.19.2-1.4.0:

Time: 2023-12-13 13:08:32
Description: Saving entity NBT

_java.lang.NullPointerException: Cannot invoke "dev.prognitio.pa3.capabililty.AbilityType.toString()" because "this.incendiaryLance" is null_

Rolling back to version 1.3.1 doesn't cause any issues. Please let me know if you'd prefer I add my crash log as well.

Thank you!

**Comment by iriskopecky** [comment]
No a crash report shouldn't be necessary. With the way player data is loaded, I think the new abilities are expected to exist but don't yet. Will work on this later today I hope. Thanks!

**Comment by iriskopecky** [comment]
This is now fixed in the newest version! Thanks for the info. Be aware Curseforge and/or Modrinth might take a little while to show the new version. Enjoy!
